#spring.application.name=eureka-server
#server.port=9001
#eureka.instance.hostname=localhost
#关闭自我注册
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
#关闭保护模式并定时清理
#eureka.server.enable-self-preservation=false
#eureka.server.eviction-interval-timer-in-ms=5000
spring:
  application:
    name: eureka-server
server:
  port: 9000
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://peer2:9001/eureka/,http://peer3:9002/eureka/
---
spring:
  profiles: peer1
  application:
    name: eureka-server
server:
  port: 9000
eureka:
  instance:
    hostname: peer1
    serviceUrl:
      defaultZone: http://peer2:9001/eureka/,http://peer3:9002/eureka/
---
spring:
  profiles: peer2
  application:
    name: eureka-server
server:
  port: 9001
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:9001/eureka/,http://peer3:9002/eureka/
---
spring:
  profiles: peer3
  application:
    name: eureka-server
server:
  port: 9002
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: http://peer2:9001/eureka/,http://peer3:9002/eureka/